### PR TITLE
Fix Windows Hello popup position

### PR DESCRIPTION
**Pull request by davidegiacometti**
Open Windows Hello popup centered on main desktop
Fixes https://github.com/sirAndros/KeePassWinHello/issues/54

EDIT: not working properly on Windows 11

### CODE REVIEW

**Comment by SilveIT** [comment]
Hi. Have you tried using GetForegroundWindow? As we are autotyping in the foreground window the windows hello dialog should also popup in that window. Not quite sure what are you trying to achieve with the GetDesktopWindow...

**Comment by davidegiacometti** [comment]
Hi,
I think `GetForegroundWindow` have more sense.
The main problem is that this is working on Windows 10, but on Windows 11 the Windows Hello popup steal the focus to KeePass.

**Comment by SilveIT** [comment]
So.. If the fix won't work on W11 it will still work on W10 at least. Right? Fixing it on the W11 just will be another thing.
I suggest you creating a pull request with the W10 fix (still recommend trying the GetForegroundWindow).

**Comment by sirAndros** [comment]
Hi!
Please consider existing code: https://github.com/sirAndros/KeePassWinHello/blob/master/src/Utilities/Win32Window.cs#L178

**Pull request closed without merging**
